### ISSUE TITLE
Error with new update

### ISSUE THREAD

**Issue by Martystl** [flingo64/PhotoStation-Upload-Lr-Plugin#24] opened 2017-10-05 14:30 UTC
I finally updated to the new software, was getting tired of all of the messages.  But, the new software is NOT working.  I am running it and the software runs for about 10 - 15 photos, then I get a message:

Photo StatLr: That does it, I'm leaving!
An internal error has occurred: {string "PSUploadTask.lua"}:289: bad argument # 1 to 'find' (string expected, got nil).

I copied the new software over to the existing folder.  I have tried several things to no avail.  

I have ran the software 5 or 6 times, it continues and more pictures uploaded, but run 10 to 15 pictures each time then receive the above error.
Thanks
Marty

**Comment by flingo64** [comment] 2017-10-05 23:08
Hi Marty,
the exception is caused by a video, right? It's probably not an issue of the new version, but of this particular video. Please, send me the logfile of the upload exception with loglevel set to Debug, so I can look into that issue.

**Comment by Martystl** [comment] 2017-10-07 13:21
The error I don’t believe is because of a video.  I do have on video, but I continue running the program and another 10 or so photo’s would be uploaded before it errored out.

 

I removed the collection, then deleted the publish service, then sat things back up and it is working.  I did screen shots of the previous version and noticed that the new version has “private comments” and “public comments”.  The previous version didn’t have both of these.  Before I deleted the collection, both were checked.    I have only the “public” comments checked.  Not sure if this resolved the issue or if deleting and recreating everything resolved this issue.

 

Thanks for the response.  Love the software.  Will be making another donation for this great software. 

 

Thanks

Marty

**Comment by flingo64** [comment] 2017-10-07 21:19
The code line 
> {string  "PSUploadTask.lua"}:289
 causing the exception is definitely dealing with video upload, but the misbehaviour may be caused somewhere else. 
Private and public comment download settings should not have an influence in this particular case.
Anyway, if the re-setup of the collection did fix the issue, I'll close the issue for the moment.

**Closed by flingo64** 2017-10-07 21:19 UTC
