### ISSUE TITLE
downloading comments / keywords does not work

### ISSUE THREAD

**Issue by danielbierstedt** [flingo64/PhotoStation-Upload-Lr-Plugin#21] opened 2017-07-23 17:51 UTC
During re-publishing, the download of comments and meta changes hangs. After the message in the attachment, the progress bar stays forever.

![photo statlr meta download issue](https://user-images.githubusercontent.com/9999431/28501619-0f46940a-6fe0-11e7-8159-3ef6ed2e7114.PNG)

**Comment by flingo64** [comment] 2017-07-23 19:16
Hi Daniel,
I need more info. Please, set loglevel to Debug and attach the logfile.

BTW, you can quit the progress bar by clicking the x

**Comment by danielbierstedt** [comment] 2017-07-24 15:16
So you say the process works in the backgroud and the Lr progress bar does not reflect the actual progress of the process? Or only if I want it to end no matter what the result was?
[Photo StatLR.zip](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/1170264/Photo.StatLR.zip)

**Comment by flingo64** [comment] 2017-07-24 23:02
No, the plugin really died during the process of downloading ratings/metadata. Since there is no way for the plugin to catch any exception in that particular process, the progress bar is not cleaned up, so you have to do it by yourself.

The exception is caused by a bug  dealing with the synchronization of face regions between Lr and PS. In fact, I could identify at least two bugs there: 
- handling of regions name that include a blank (e.g. 'Name Surname') is incorrect
- exception handling for a failed exiftool query is missing
I will fix it in the next release.

Anyway, are you sure you are going to create face regions in PS and want to re-import them to Lr? If so, did you read the [notes on synching person tags / face region metadata](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/wiki/Publish:-Some-words-on-the-two-way-sync-of-metadata#supported-metadata). 
If not, I would suggest to disable the download faces option

**Comment by danielbierstedt** [comment] 2017-07-26 17:00
Yea, I did more testing and I noticed, it is with the face stuff. When I disable the face re-import, the process dies some time later. But in the end, I did not manage to get PS meta changes back into Lr and stopped testing for now.
BTW, another thing about blanks: I believe, it was in the target area where you can hit "create if not available". That does not work with a blank in it.

**Comment by flingo64** [comment] 2017-07-26 23:47
I fixed quite a lot of face region synch issues, this will be available in the next release.
I added a Target Album path validation (no leading/trailing blanks in directory names allowed, etc.) --> next release.
I also found out that 'exiftool(-k).exe' as path for exiftool is bad, because it prevents the plugin to stop the exiftool background process, so you will end up with lots of exiftool processes after a while. You should rename it or copy it to 'exiftool.exe'. --> Readme of next version.
 
If you still have issue with metadata downloads, you may send a logfile to the PhotoStatLr contact (see Readme --> Support Page.

**Comment by flingo64** [comment] 2017-08-02 19:42
Should be fixed in Version 6.4.2.
Please retest!

**Comment by danielbierstedt** [comment] 2017-08-08 17:11
Ok, now... I had some time to test today.
- the process runns and finishes without issues
- color codes are being translated from PS to Lr, but only if they've been written in the form of "+blue" as a general tag
- native PS color codes are not being translated from PS to Lr
- color codes are not being translated from Lr to PS
- ratings (stars) are being translated both ways successfully

I would say, so far, so good and you may close this issue. Do you have a "feature request" section somewhere? That would be about translating native color codes from PS to Lr. Reason is to let users choose colors for images that get translated into the Lr catalogue so I can work on the selection. That would basically a yes/no selection for others, but my workflow is that all "blue" images are wishes and all "green" are done and ready for delivery.

**Comment by flingo64** [comment] 2017-08-08 20:52
> native PS color codes are not being translated from PS to Lr

Are you talking about the color labels in Public Shared Albums? Right, these labels are not handled by  the color label translation mechanism. Comments on that issue, see below.

> color codes are not being translated from Lr to PS

If you check 'Color Label Tags' upload option, the Lr color label will be translated to a PS general tag like '+blue'. Just checked it, it still works.

I will close this issue and open a new one (feature request) for the "Synchronization of color labels from Public Shared Albums".  This is a feature which was already asked for by others and I also have my own thoughts on it. So, it will probably need some discussions of how-to-do. You're invited ...

**Closed by flingo64** 2017-08-08 20:52 UTC
